package sample.common.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import sample.common.dao.entity.User;
import sample.common.dao.entity.UserExample;

@Mapper
public interface UserMapper {

    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	long countByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	int deleteByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	int deleteByPrimaryKey(String user_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	int insert(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	int insertSelective(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	List<User> selectByExampleWithBLOBs(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	List<User> selectByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	User selectByPrimaryKey(String user_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	int updateByExampleSelective(@Param("row") User row, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	int updateByExampleWithBLOBs(@Param("row") User row, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	int updateByExample(@Param("row") User row, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	int updateByPrimaryKeySelective(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	int updateByPrimaryKeyWithBLOBs(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	int updateByPrimaryKey(User row);

	// Add Start
    User userSearch(User user);
    // Add End
}