package sample.common.dao.entity;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public UserExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUser_idIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUser_idIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUser_idEqualTo(String value) {
			addCriterion("user_id =", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idNotEqualTo(String value) {
			addCriterion("user_id <>", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idGreaterThan(String value) {
			addCriterion("user_id >", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idLessThan(String value) {
			addCriterion("user_id <", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idLike(String value) {
			addCriterion("user_id like", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idNotLike(String value) {
			addCriterion("user_id not like", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idIn(List<String> values) {
			addCriterion("user_id in", values, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idNotIn(List<String> values) {
			addCriterion("user_id not in", values, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_nameIsNull() {
			addCriterion("user_name is null");
			return (Criteria) this;
		}

		public Criteria andUser_nameIsNotNull() {
			addCriterion("user_name is not null");
			return (Criteria) this;
		}

		public Criteria andUser_nameEqualTo(String value) {
			addCriterion("user_name =", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameGreaterThan(String value) {
			addCriterion("user_name >", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameLessThan(String value) {
			addCriterion("user_name <", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameLike(String value) {
			addCriterion("user_name like", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameNotLike(String value) {
			addCriterion("user_name not like", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameIn(List<String> values) {
			addCriterion("user_name in", values, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameNotIn(List<String> values) {
			addCriterion("user_name not in", values, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "user_name");
			return (Criteria) this;
		}

		public Criteria andEmail_addressIsNull() {
			addCriterion("email_address is null");
			return (Criteria) this;
		}

		public Criteria andEmail_addressIsNotNull() {
			addCriterion("email_address is not null");
			return (Criteria) this;
		}

		public Criteria andEmail_addressEqualTo(String value) {
			addCriterion("email_address =", value, "email_address");
			return (Criteria) this;
		}

		public Criteria andEmail_addressNotEqualTo(String value) {
			addCriterion("email_address <>", value, "email_address");
			return (Criteria) this;
		}

		public Criteria andEmail_addressGreaterThan(String value) {
			addCriterion("email_address >", value, "email_address");
			return (Criteria) this;
		}

		public Criteria andEmail_addressGreaterThanOrEqualTo(String value) {
			addCriterion("email_address >=", value, "email_address");
			return (Criteria) this;
		}

		public Criteria andEmail_addressLessThan(String value) {
			addCriterion("email_address <", value, "email_address");
			return (Criteria) this;
		}

		public Criteria andEmail_addressLessThanOrEqualTo(String value) {
			addCriterion("email_address <=", value, "email_address");
			return (Criteria) this;
		}

		public Criteria andEmail_addressLike(String value) {
			addCriterion("email_address like", value, "email_address");
			return (Criteria) this;
		}

		public Criteria andEmail_addressNotLike(String value) {
			addCriterion("email_address not like", value, "email_address");
			return (Criteria) this;
		}

		public Criteria andEmail_addressIn(List<String> values) {
			addCriterion("email_address in", values, "email_address");
			return (Criteria) this;
		}

		public Criteria andEmail_addressNotIn(List<String> values) {
			addCriterion("email_address not in", values, "email_address");
			return (Criteria) this;
		}

		public Criteria andEmail_addressBetween(String value1, String value2) {
			addCriterion("email_address between", value1, value2, "email_address");
			return (Criteria) this;
		}

		public Criteria andEmail_addressNotBetween(String value1, String value2) {
			addCriterion("email_address not between", value1, value2, "email_address");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table postgres.user
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table postgres.user
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 17 18:04:26 JST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}