package sample.common.dao.entity;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column postgres.user.user_id
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	private String user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column postgres.user.user_name
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	private String user_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column postgres.user.email_address
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	private String email_address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column postgres.user.password
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	private byte[] password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column postgres.user.user_id
	 * @return  the value of postgres.user.user_id
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public String getUser_id() {
		return user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column postgres.user.user_id
	 * @param user_id  the value for postgres.user.user_id
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public void setUser_id(String user_id) {
		this.user_id = user_id == null ? null : user_id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column postgres.user.user_name
	 * @return  the value of postgres.user.user_name
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public String getUser_name() {
		return user_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column postgres.user.user_name
	 * @param user_name  the value for postgres.user.user_name
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public void setUser_name(String user_name) {
		this.user_name = user_name == null ? null : user_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column postgres.user.email_address
	 * @return  the value of postgres.user.email_address
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public String getEmail_address() {
		return email_address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column postgres.user.email_address
	 * @param email_address  the value for postgres.user.email_address
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public void setEmail_address(String email_address) {
		this.email_address = email_address == null ? null : email_address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column postgres.user.password
	 * @return  the value of postgres.user.password
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public byte[] getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column postgres.user.password
	 * @param password  the value for postgres.user.password
	 * @mbg.generated  Sat Oct 21 07:28:47 JST 2023
	 */
	public void setPassword(byte[] password) {
		this.password = password;
	}
}