services:

#=========================================================
# nginx
#=========================================================
  nginx:
    build:
      context: ./containers/nginx
    ports:
      - "80:80"
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet
    depends_on:
      - node
      - spring
    restart: always

#=========================================================
# node
#=========================================================
  node:
    build: 
       context: ./containers/node
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./containers/node:/app
    networks:
      - webnet
    environment:
      - NODE_ENV=production
    depends_on:
      - keycloak
    restart: always
    
#=========================================================
# spring
#=========================================================
  spring:
    build: 
      context: ../..
      dockerfile: debelopTools/Docker/containers/spring/Dockerfile # Dockerfile のパスを指定します。
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres
      - redis
    networks:
      - webnet  
    restart: always

#=========================================================
# redis
#=========================================================
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - webnet  
    restart: always

#=========================================================
# keycloak
#=========================================================
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest 
    command: start-dev --http-port=8080
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin_password
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak_password
    volumes:
      - ./containers/keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf
    depends_on:
      - postgres  
    networks:
      - webnet  
    restart: always

#=========================================================
# database postgresql
#=========================================================
  postgres:
    build: ./containers/postgres
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      # データ永続化のためのボリューム追加
      - ./containers/postgres/data:/var/lib/postgresql/data 
      - ./containers/postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak_password
      - POSTGRES_DB=keycloak
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    networks:
      - webnet  
    restart: always
    user: postgres
    
networks:
  webnet:
    driver: bridge