version: "3"
services:

#=========================================================
# nginx
#=========================================================
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    restart: always

#=========================================================
# node
#=========================================================
  node:
    build: 
       context: ./containers/node
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./node:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - keycloak
    restart: always
    
#=========================================================
# spring
#=========================================================
  spring:
    build: 
      context: ./containers/spring
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres
      - redis
    restart: always

#=========================================================
# redis
#=========================================================
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

#=========================================================
# keycloak
#=========================================================
  keycloak:
    image: jboss/keycloak
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    restart: always

#=========================================================
# database postgresql
#=========================================================
  postgres:
    build: ./containers/postgres
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      # データ永続化のためのボリューム追加
      - ./containers/postgres/data:/var/lib/postgresql/data 
      - ./containers/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: postgres
